apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2021-09-06T21:55:26Z"
  generation: 494
  name: wordpress-app
  namespace: argocd
  resourceVersion: "377592"
  uid: f0e19826-a4d7-4359-aa0d-fa697977408b
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc
  project: default
  source:
    path: wordpress/overlays/amd64
    repoURL: git@github.com:rwellinger/kubernetes-playground.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
status:
  health:
    status: Healthy
  history:
  - deployStartedAt: "2021-09-06T21:55:29Z"
    deployedAt: "2021-09-06T21:55:30Z"
    id: 0
    revision: ae5751581a4c7c0251d2bf7f53eb1580e6dee62c
    source:
      path: wordpress/overlays/amd64
      repoURL: git@github.com:rwellinger/kubernetes-playground.git
      targetRevision: HEAD
  operationState:
    finishedAt: "2021-09-06T21:55:30Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: ae5751581a4c7c0251d2bf7f53eb1580e6dee62c
    phase: Succeeded
    startedAt: "2021-09-06T21:55:29Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/wordpress configured
        name: wordpress
        namespace: wordpress
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Secret
        message: secret/mariadb-secret configured
        name: mariadb-secret
        namespace: wordpress
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: PersistentVolumeClaim
        message: persistentvolumeclaim/mysql-pv-claim configured
        name: mysql-pv-claim
        namespace: wordpress
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: PersistentVolumeClaim
        message: persistentvolumeclaim/wp-pv-claim configured
        name: wp-pv-claim
        namespace: wordpress
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/wordpress-mysql configured
        name: wordpress-mysql
        namespace: wordpress
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/wordpress configured
        name: wordpress
        namespace: wordpress
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/wordpress-mysql configured
        name: wordpress-mysql
        namespace: wordpress
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/wordpress configured
        name: wordpress
        namespace: wordpress
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/wordpress-ingress configured
        name: wordpress-ingress
        namespace: wordpress
        status: Synced
        syncPhase: Sync
        version: v1
      revision: ae5751581a4c7c0251d2bf7f53eb1580e6dee62c
      source:
        path: wordpress/overlays/amd64
        repoURL: git@github.com:rwellinger/kubernetes-playground.git
        targetRevision: HEAD
  reconciledAt: "2021-09-07T22:13:51Z"
  resources:
  - kind: Namespace
    name: wordpress
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: PersistentVolumeClaim
    name: mysql-pv-claim
    namespace: wordpress
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: PersistentVolumeClaim
    name: wp-pv-claim
    namespace: wordpress
    status: Synced
    version: v1
  - kind: Secret
    name: mariadb-secret
    namespace: wordpress
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: wordpress
    namespace: wordpress
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: wordpress-mysql
    namespace: wordpress
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: wordpress
    namespace: wordpress
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: wordpress-mysql
    namespace: wordpress
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: wordpress-ingress
    namespace: wordpress
    status: Synced
    version: v1
  sourceType: Kustomize
  summary:
    externalURLs:
    - https://www.thwelly.net/
    images:
    - mariadb:10.5.12
    - wordpress:php8.0-apache
  sync:
    comparedTo:
      destination:
        namespace: wordpress
        server: https://kubernetes.default.svc
      source:
        path: wordpress/overlays/amd64
        repoURL: git@github.com:rwellinger/kubernetes-playground.git
        targetRevision: HEAD
    revision: 9575e8b40abba17406bcb287cc8c2a2db28e6c17
    status: Synced
